#!/bin/bash

DOCKER="docker"
if [ "$DEBUG" == "1" ]; then
	DOCKER="echo docker"
fi

REPO=${DOCKER_REPO:-"astlab/launchpad"}
TAG=${SOURCE_BRANCH:-$(date '+%y.%m')}

while read -r TARGET; do
	if [[ -z "$TARGET" || "$TARGET" =~ ^\#.* ]]; then
		continue
	fi
	$DOCKER build -f ./$TARGET/Dockerfile -t $REPO:$TARGET-$TAG ./$TARGET/
done < "release/$TAG"
