#!/bin/bash

REPO=${DOCKER_REPO:-"astlab/launchpad"}
TAG=${SOURCE_BRANCH:-$(date '+%y.%m')}

# pretest
while read -r TARGET; do
	# skip comments
	if [[ -z "$TARGET" || "$TARGET" =~ ^\#.* ]]; then
		continue
	fi
	# check dockerfile
	PATH="./$TARGET/Dockerfile"
	if [ ! -f "$PATH" ]; then
		echo "Dockerfile not found at: $PATH"
		exit 1
	fi
done < "release/$TAG"

# build
while read -r TARGET; do
	# skip comments
	if [[ -z "$TARGET" || "$TARGET" =~ ^\#.* ]]; then
		continue
	fi
	# build
	docker build -f ./$TARGET/Dockerfile -t $REPO:$TARGET-$TAG ./$TARGET/
done < "release/$TAG"
