#!/bin/bash

REPO=${DOCKER_REPO:-"astlab/launchpad"}
TAG=${SOURCE_BRANCH:-$(date '+%y.%m')}

while read -r TARGET; do
	if [[ -z "$TARGET" || "$TARGET" =~ ^\#.* ]]; then
		continue
	fi
	PATH="./$TARGET/Dockerfile"
	if [ ! -f "$PATH" ]; then
		echo "Dockerfile not found at: $PATH"
		exit 1
	fi
done < "release/$TAG"
